--- # creating multiple users
- hosts: all
  become: true


  tasks: 
    - name: creating multiple user accounts
      user: name='{{item}}' state=present
      with_items:
            - Raj
            - Pawan
            - Hari
            - Atif
            - Sai
            
