--- # install java / download tomcat & install
- hosts: webservers
  become: yes
  user: ansible
  connection: ssh

  tasks:
    - name: install java s/w on redhat
      yum:
        name: java
        state: installed
      when: ansible_os_family == "RedHat"

    - name: Install java s/w on Debian
      apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: download tomcat software
      get_url: 
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.87/bin/apache-tomcat-8.5.87.tar.gz
        dest: /opt
   
    - name: extract tomcat software
      unarchive:
        src: /opt/apache-tomcat-8.5.87.tar.gz
        dest: /opt
        remote_src: yes

    - name: providing executable permissions
      file: 
        path: /opt/apache-tomcat-8.5.87/bin/startup.sh
        mode: 0777

    - name: start tomcat service
      shell: nohup ./startup.sh
      args: 
        chdir: /opt/apache-tomcat-8.5.87/bin

